### ISSUE TITLE
Error while mutate exe

### ISSUE THREAD

**Issue by ghost** [nelfo/Milfuscator#1]
Output -

[+] Functions loaded!
[+] Analyzing functions...
[+] Analyzed 11469 functions!
[+] Rebuilding binary...
[+] Unknown mnemonic! | 301

How to fix it?

**Comment by nelfo** [comment]
Hi, this error is due to JCXZ instruction that my rebuilder doesn't handle. You can try to fix this error by uncommenting line 76 in the Rebuilder.cpp file. I don’t remember exactly why I commented it out, most likely the asmjit library could not assemble this instruction. If this method does not help, then you can somehow get rid of this instruction by changing part of the program code. Load your program in IDA, load the pdb file of the program, find this instruction in the assembler and see in which function this instruction was generated after compilation. You can also try turning off compile-time optimizations to fix this.

Let me remind you that this mutator is very unstable and not all exe files will be able to run after the mutation.
